---
functional:
  - Пользователь должен иметь возможность решать задачи на скорость против другого игрока.
  - Игра может быть проведена с любым человеком, с ботом или другом
  - Пользователь должен иметь возможность менять сложность игры
  - Пользователь должен иметь возможность выбрать время игры во вемя ее создания
  - Другие пользователи могут следить за ходом любой игры онлайн
  - Пользователи должны иметь возможность просматривать записи завершенных игр
  - Пользователи должны иметь возможность вести переписку в чате после регистрации
  - Сайт должен иметь систему очков за проведенные игры
  - Пользователь должен иметь возможность видеть результат игры по ее окончанию
  - Пользователь может иметь возможность регистрироваться на сайте и входить в свой аккаунт
  - Пользователь должен иметь возможность восстановить пароль при утере
  - Пользователь должен иметь возможность менять свои данные профиля
  - Пользователь может присоединяться к игре по приглашению
  - Пользователь должен иметь возможность писать приватные сообщения другому игроку
  - Пользователь должен иметь возможность добавлять новые задачи и группировать уже созданные
non-functional:
  - Сайт должен быть разработан с учетом удобства использования
  - Главная страница сайта должна полностью загружаться менее чем за 10 секунды
  - Отправка кода на проверку и получение результата должны занимать не более 5 секунд
  - Сайт должен использовать HTTPS на всех страницах
  - Сайт должен быть защищен от SQL-инъекций и XSS-атак в полях ввода
  - Сайт должен корректно отображаться и быть полностью функциональным на экранах с маленькой шириной без появления горизонтальной прокрутки.
  - Сайт должен быть совместим с последними версиями браузеров Chrome, Firefox, Safari
  - Сайт должен быть способен обрабатывать 1000 одновременных пользователей
  - Сайт должен поддерживать русский и английские языки
  - Все интерактивные элементы должны иметь визуальную обратную связь
implicit:
  - При переключении языка весь интерфейс должен меняться на выбранный язык
  - Пользователь должен видеть историю сообщений в чате
  - Пользователь в игре должен иметь возможность проверять свой код в игре
  - Пользователь должен иметь возможность найти себя в рейтинговой таблице
